services:
  db:
    image: postgres:14
    container_name: dashboard-db-prod
    environment:
      POSTGRES_DB: dashboard_db_prod
      POSTGRES_USER: user        
      POSTGRES_PASSWORD: password  
    ports:
      - "5433:5432"              
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./dashboard-api    
    container_name: dashboard-api-prod
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/dashboard_db_prod
      DB_USER: user             
      DB_PASSWORD: password      

  frontend:
    build:
      context: ./front-end       
    container_name: dashboard-frontend-prod
    ports:
      - "5173:5173"                
    depends_on:
      - backend

  recipe-api:
    build:
      context: ./recipe-api  
    container_name: recipe-api-prod
    ports:
      - "8081:8081"  

volumes:
  postgres_data: